### ISSUE TITLE
pmp_42 translation incorrect

### ISSUE THREAD

**Issue by alecjacobson** [i-heart-la/i-heart-la.github.io#1]
I can't make sense of the current I❤️LA code for the pmp_42 example in the gallery. Why is T_i a real-valued 3x3 matrix? What does the _i refer to under T?

I propose replacing this code with a more straightforward translation:

```I❤️LA 
given
α_T : ℝ
n_T : ℝ³

`n(v)` = ( ∑_(T for T ∈ `N₁`(v)) α_T n_T )/‖ ∑_(T for T ∈ `N₁`(v)) α_T n_T ‖

where
v ∈ ℤ
`N₁` : ℤ → {ℤ}
```

This matches my reading of the source material: we're given a list of per-triangle weights (`α_T`) and per-triangle normal vectors (`n_T`) and a particular vertex (`v`) for which we compute the weighted average of incident face (`N₁`) normals. The output LaTeX looks a bit different because `T` becomes a subscript rather than a `(T)`. Alternatively we could define `α : ℤ → ℝ` and `n : ℤ → ℝ³` as functions. (We're stuck a bit here because the original expression is using `n` for a function mapping from two very different domains (set of vertices `v` and set of faces `T`).

**Comment by alecjacobson** [comment]
(currently my proposal does not result in correct target code due to https://github.com/pressureless/linear_algebra/issues/64 )

**Comment by alecjacobson** [comment]
Functions with a single integer parameter `ℤ →` is a bit silly to implement as a _function_ if we expect the domain to be a dense range like this. So maybe an even better translation is:

given
α_T : ℝ
n_T : ℝ³

`n(v)` = ( ∑_(T for T ∈ `N₁`_v) α_T n_T )/‖ ∑_(T for T ∈ `N₁`_v) α_T n_T ‖

where
v ∈ ℤ
`N₁`_i :  {ℤ}

**Comment by pressureless** [comment]
Why is T_i a real-valued 3x3 matrix? What does the _i refer to under T?

Previously I thought `T_i` is a sequence of triangles, for each triangle, the `3x3` matrix stores the 3 vertex positions

**Comment by i-heart-la** [comment]
Fixed
