### ISSUE TITLE
[minor] [multi_frame_1] match use of ⋅ in source

### ISSUE THREAD

**Issue by alecjacobson** [i-heart-la/i-heart-la.github.io#15]
The source uses `⋅` for scalar multiplication. Since we support that, we might as well use it, too.
```
`C(x,y)` = (∑_n ∑_i c_n,i ⋅ w_n,i ⋅ R̂_n) / (∑_n ∑_i w_n,i ⋅ R̂_n)

where

c ∈ ℝ^(f×s) : the value of the Bayer pixel
w ∈ ℝ^(f×s) : the local sample weight
R̂ ∈ ℝ^f     : the local robustness
```

We could also include a screenshot of the next paragraph in the paper since that's where these terms get defined: 
![image](https://user-images.githubusercontent.com/2241689/118410267-8fc17980-b65c-11eb-9c08-ea83361ba6d1.png)

**Comment by pressureless** [comment]
Fixed

**Comment by alecjacobson** [comment]
Should we also include this longer screenshot with the definitions?

**Comment by pressureless** [comment]
Sorry that I missed that part.

**Comment by pressureless** [comment]
Fixed
