### ISSUE TITLE
[minor] [convex_optimization_384] confusing swap of m and n

### ISSUE THREAD

**Issue by alecjacobson** [i-heart-la/i-heart-la.github.io#6]
In the source, n is the dimension of x and and y_i, and m is the number of y_i,w_i pairs. In our translation we swap m and n. I propose we switch our translation to:

```I❤️LA
given
a_i ∈ ℝ^n : the measurement vectors  
x ∈ ℝ^n   : original vector 
w_i ∈ ℝ   : measurement noise 

y_i = a_iᵀ x + w_i
x̂ = (∑_i a_i a_iᵀ)⁻¹ ∑_i y_i a_i
```

(not sure how to get the `x̂` to appear correctly on github markdown...)

**Comment by pressureless** [comment]
Fixed
