### ISSUE TITLE
[convex_optimization_650] use generic sizes and include def of S

### ISSUE THREAD

**Issue by alecjacobson** [i-heart-la/i-heart-la.github.io#7]
convex_optimization_650 hard codes square 4x4 blocks. In particular `B` does not need to be square and `A` does not need to be the same size as `C`.

This example is more interesting if we also include the definition of the schur complement S (equation a few lines up in the source).

 I propose we use instead.
 
 ```
 given
A ∈ ℝ^(m×m) 
B ∈ ℝ^(m×n) 
C ∈ ℝ^(n×n) 

S = C - BᵀA⁻¹B
[A⁻¹+A⁻¹BS⁻¹BᵀA⁻¹   -A⁻¹BS⁻¹
    -S⁻¹BᵀA⁻¹           S⁻¹]
 ```

(currently this is blocked by a[ parsing bug](https://github.com/pressureless/linear_algebra/issues/70))

**Comment by pressureless** [comment]
Fixed
